name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Use Node.js 16.x 🐧
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Build and test 🔧
        run: |
          npm ci
          npx eslint src --ext .js,.jsx,.ts,.tsx
          npx tsc --project .
          npm run build --if-present
          npm test -- --coverage

      - name: Upload code coverage 🚀
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true
